### ISSUE TITLE
RDFJS compliance: blank node values should not be prepended by `_:`

### ISSUE THREAD

**Issue by pietercolpaert** [digitalbazaar/jsonld.js#244] opened 2018-04-24 15:59 UTC
[RDFJS defines in its specification](http://rdf.js.org/#x2-3-blanknode-interface) that:

> value blank node name as a string, without any serialization specific prefixes, e.g. when parsing, if the data was sourced from Turtle, remove "_:", if it was sourced from RDF/XML, do not change the blank node name (example: "blank3")

However, jsonld.js does not remove `_:` when executing the toRDF code. This can be found in multiple places. One example: https://github.com/digitalbazaar/jsonld.js/blob/c6501fbf44cd9d5a589212f9428c0573ae40ada2/lib/toRdf.js#L103

**Comment by dlongley** [comment] 2020-05-26 23:23
Closing as not a bug. If there's an actual bug here, please re-open and provide a test case with expected output and actual output that does not match.

**Closed by dlongley** 2020-05-26 23:23 UTC

**Comment by joeltg** [comment] 2020-08-09 01:17
I also care about this issue! Right now, anybody trying to integrate jsonld.js with any other popular RDF library like [n3.js](https://github.com/rdfjs/N3.js) has to manually run some snippet like this on the output of `toRDF`:

```javascript
const dataset = await jsonld.toRDF(doc, {})
for (const quad of dataset) {
	if (quad.subject.value.startsWith("_:")) {
		quad.subject.value = quad.subject.value.slice(2)
	}
	if (quad.object.value.startsWith("_:")) {
		quad.object.value = quad.object.value.slice(2)
	}
	if (quad.graph.value.startsWith("_:")) {
		quad.graph.value = quad.graph.value.slice(2)
	}
}
// *now* we can import `dataset` into an n3.js store...
```

... which is really annoying!

A concrete test case would be:

```javascript
jsonld.toRDF({ "http://schema.org/knows": { "@id": "_:b1" } }, {})
```

which produces

```javascript
[
  {
    subject: { termType: 'BlankNode', value: '_:b0' },
    predicate: { termType: 'NamedNode', value: 'http://schema.org/knows' },
    object: { termType: 'BlankNode', value: '_:b1' },
    graph: { termType: 'DefaultGraph', value: '' }
  }
]
```

but _should_ produce

```javascript
[
  {
    subject: { termType: 'BlankNode', value: 'b0' },
    predicate: { termType: 'NamedNode', value: 'http://schema.org/knows' },
    object: { termType: 'BlankNode', value: 'b1' },
    graph: { termType: 'DefaultGraph', value: '' }
  }
]
```

The relevant portion of the RDFJS spec was quoted in the original comment - the jsonld.js documentation doesn't explicitly mention RDFJS anywhere as far as I can tell, but it's clearly the intended representation.

**Comment by tpluscode** [comment] 2024-02-26 20:52
@pietercolpaert would you mind reopening this? This is in fact a problem which bit me more than once

**Comment by pietercolpaert** [comment] 2024-02-26 20:58
I cannot re-open this very issue - please check with @dlongley who indicated a couple of years ago a new issue with a proposal for a PR with a test case will do the trick.

Today I just use https://github.com/rubensworks/jsonld-streaming-parser.js instead

**Comment by dlongley** [comment] 2024-02-26 21:19
PR #548 might address this, I'm not sure.

**Comment by davidlehn** [comment] 2024-02-26 23:06
The `rdf-canonize` internals were changed to hopefully address this issue around here: https://github.com/digitalbazaar/rdf-canonize/commit/b36b1c9f1b6d2d2a050fb6f33898493999071b66.  Fixing and updating `jsonld.js` to use the newer `rdf-canonize` has dragged on longer than expected (we're busy).  Hopefully when that is merged it will fix the issue.  That PR could certainly use some testing if you have the time.

Also I don't think `jsonld.promises` is needed anymore?  The main calls should be async.
