### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by jeroen** [digitalbazaar/jsonld.js#159] opened 2016-12-10 17:35 UTC
I wrote some bindings to `jsonld.js` for the R programming language, but I noticed that many of the unit tests from the [json-ld website](http://json-ld.org/test-suite/) are failing. Is this expected or am I doing something wrong?

**Comment by harlantwood** [comment] 2016-12-11 22:59
#156

**Comment by jeroenooms** [comment] 2016-12-12 12:01
I am not sure all of my failures are due to that problem. Perhaps I am doing something wrong. Below a report of the failed unit tests:

 - https://gist.github.com/jeroenooms/bab74905622c6621ffe64ddb4481a393

Note that I run the unit tests locally, and I set the `base` option to whatever is set in the `baseIri` field of the corresponding `test-manifest.jsonld` file. Should I set additional options?

Sometimes the problem is somewhat difficult to notice. For example the first test fails because the relative link gets parsed as `"compact-0066-in.jsonld#fragment-works"` instead of `"#fragment-works"`.

**Comment by jeroenooms** [comment] 2016-12-12 20:28
I have updated my results. More tests are passing now. I wasn't properly passing along the `option` field from the manifest to the bindings.

However I still get a lot of failures for `jsonld.frame`. See here:

 - https://github.com/ropensci/jsonld/blob/master/tests/testthat/report.md

Should I be passing certain additional options to `jsonld.frame` to run the unit tests?

**Comment by dlongley** [comment] 2017-01-05 18:07
Update: We'll be doing some build/test subsystem rewrites that will involve fixing these issues (at least by skipping the appropriate tests for now) fairly soon. cc: @davidlehn

**Comment by davidlehn** [comment] 2017-01-12 22:40
I added support to skip the 1.1 and framing tests so that part should work for now.

It's also cheating and skipping the failing RFC3986 tests.  An issue was opened for that:
https://github.com/digitalbazaar/jsonld.js/issues/160

**Comment by dlongley** [comment] 2020-05-26 21:48
This should be resolved now, closing.

**Closed by dlongley** 2020-05-26 21:48 UTC
