### ISSUE TITLE
package.json main points to library instead of compiled file in dist

### ISSUE THREAD

**Issue by peacememories** [digitalbazaar/jsonld.js#251] opened 2018-06-15 11:30 UTC
Jsonld uses spread operators as part of its code base. These operators are transformed to a more compatible version of javascript in the `dist/jsonld.js` version.
The problem is that the `package.json` points to the uncompiled entrypoint, which means any consumer of the library needs to either support spread operators or manually compile the library code. We ran into this with our webpack build [here](https://github.com/researchstudio-sat/webofneeds/issues/1533), because we exclude everything in `node_modules` from transformation (which is typically done). Our workaround right now is to remap every import of `jsonld` to `jsonld/dist/jsonld.js`, but I would love to be able to remove this hack :)

**Comment by davidlehn** [comment] 2018-06-15 16:12
This is a general problem with the entire js ecosystem.  Do you know of a solution?  We also use hacks like overriding where to look for the code.  The source should be used when it makes sense, so "main" should point to that.  In the future, when things are ES modules, you'd want to use the main entry point to get tree shaking optimizations and similar.  We did add support for node6, so the main index.js will jump to that babeled code if needed.  The "browser" field seems to be poorly specified, doesn't handle all use cases at once, and seems incompatible between browserify, webpack, systemjs, and others.  If anyone has a solution, please let us know.  We'd use it for other libs too.

**Comment by dlongley** [comment] 2020-05-26 21:41
Closing as a duplicate of #399.

**Closed by dlongley** 2020-05-26 21:41 UTC
