### ISSUE TITLE
HTTP Link Header not being parsed

### ISSUE THREAD

**Issue by msporny** [digitalbazaar/jsonld.js#70] opened 2014-09-25 00:56 UTC
The following JSON-LD document isn't being parsed correctly due to the context not being properly extracted from the Link header: http://pac.macminicolo.net:8285/rando/cayley/test.json

The JSON-LD file looks fine and seems to have the proper link header:

```console
curl -v http://pac.macminicolo.net:8285/rando/cayley/test.json
* Hostname was NOT found in DNS cache
*   Trying 199.19.85.128...
* Connected to pac.macminicolo.net (199.19.85.128) port 8285 (#0)
> GET /rando/cayley/test.json HTTP/1.1
> User-Agent: curl/7.37.0
> Host: pac.macminicolo.net:8285
> Accept: */*
> 
< HTTP/1.1 200 OK
< Accept: */*
< Accept-Ranges: bytes
< Access-Control-Allow-Headers: X-Requested-With
< Access-Control-Allow-Headers: Content-Type
< Access-Control-Allow-Methods: PUT, GET, POST, DELETE, OPTIONS
< Access-Control-Allow-Origin: *
< Content-Length: 57
< Content-Type: application/ld+json
< Last-Modified: Wed, 24 Sep 2014 22:45:26 GMT
< Link: <http://pac.macminicolo.net:8285/rando/cayley/v1.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"
< Date: Thu, 25 Sep 2014 00:49:30 GMT
< 
{
  "mylinks": [
    "url1",
    "url2",
    "url3"
  ]
}
```

The JSON-LD context seems fine too:

``` console
curl -v http://pac.macminicolo.net:8285/rando/cayey/v1.jsonld
* Hostname was NOT found in DNS cache
*   Trying 199.19.85.128...
* Connected to pac.macminicolo.net (199.19.85.128) port 8285 (#0)
> GET /rando/cayley/v1.jsonld HTTP/1.1
> User-Agent: curl/7.37.0
> Host: pac.macminicolo.net:8285
> Accept: */*
> 
< HTTP/1.1 200 OK
< Accept: */*
< Accept-Ranges: bytes
< Access-Control-Allow-Headers: X-Requested-With
< Access-Control-Allow-Headers: Content-Type
< Access-Control-Allow-Methods: PUT, GET, POST, DELETE, OPTIONS
< Access-Control-Allow-Origin: *
< Content-Length: 142
< Content-Type: application/ld+json
< Last-Modified: Wed, 24 Sep 2014 22:47:01 GMT
< Date: Thu, 25 Sep 2014 00:54:12 GMT
< 
{
  "@context": {
    "mylinks": {
      "@id": "http://pac.macminicolo.net:8285/rando/cayley/vocab#mylinks",
      "@type": "@id"
    }
  }
}
```

I added debug code everywhere that jsonld.parseLinkHeader() is called, and none of the debug code is hit. I ran out of time to debug this tonight, but it feels like a bug.

**Comment by dlongley** [comment] 2015-02-11 02:54
I believe this was resolved -- or if anything is remaining, it is a duplicate of #31. So I'm closing this out.

**Closed by dlongley** 2015-02-11 02:54 UTC
