### ISSUE TITLE
jsonld.js canonization produces different "deterministic" results between node 10.3 and node 10.4

### ISSUE THREAD

**Issue by krobi64** [digitalbazaar/jsonld.js#263] opened 2018-08-29 02:47 UTC
tested with both 1.0.2 and 1.0.4

I believe this is because you are calling `toString()` instead of the more normalizing `toISOString()` on Date objects.

```
  -_:c14n1 <http://purl.org/dcterms/created> "Mon Nov 13 2017 15:00:00 GMT+0000 (Coordinated Universal Time)" .
 +_:c14n0 <http://purl.org/dcterms/created> "Mon Nov 13 2017 15:00:00 GMT+0000 (UTC)" .
```

I have no idea why that affects the order of the document, which also troubles me.

```
 -_:c14n0 <http://schema.org/author> "Edgar Allan Poe" .
      -_:c14n0 <http://schema.org/dateCreated> "" .
      -_:c14n0 <http://schema.org/datePublished> "1845-01-29T03:00:00.000Z" .
      -_:c14n0 <http://schema.org/keyword> "poem" .
      -_:c14n0 <http://schema.org/name> "The Raven" .
      -_:c14n0 <http://schema.org/text> "Once upon a midnight dreary..." .
      -_:c14n1 <http://purl.org/dcterms/created> "Mon Nov 13 2017 15:00:00 GMT+0000 (Coordinated Universal Time)" .
      -_:c14n1 <http://schema.org/CreativeWork> _:c14n0 .
      -_:c14n1 <http://schema.org/Text> "02badf4650ba545608242c2d303d587cf4f778ae3cf2b3ef99fbda37555a400fd2" .
      -_:c14n1 <http://schema.org/additionalType> "Work" .
      +_:c14n0 <http://purl.org/dcterms/created> "Mon Nov 13 2017 15:00:00 GMT+0000 (UTC)" .
      +_:c14n0 <http://schema.org/CreativeWork> _:c14n1 .
      +_:c14n0 <http://schema.org/Text> "02badf4650ba545608242c2d303d587cf4f778ae3cf2b3ef99fbda37555a400fd2" .
      +_:c14n0 <http://schema.org/additionalType> "Work" .
      +_:c14n1 <http://schema.org/author> "Edgar Allan Poe" .
      +_:c14n1 <http://schema.org/dateCreated> "" .
      +_:c14n1 <http://schema.org/datePublished> "1845-01-29T03:00:00.000Z" .
      +_:c14n1 <http://schema.org/keyword> "poem" .
      +_:c14n1 <http://schema.org/name> "The Raven" .
      +_:c14n1 <http://schema.org/text> "Once upon a midnight dreary..." .
```

**Comment by davidlehn** [comment] 2018-08-29 03:59
What input and code are you using to get this result?  Do you have a short test case example?

It looks like the data only has string values in different date-like formats.  Nothing is typed as a date, for instance like:
```
_:c14n0 <http://schema.org/created> "2011-04-09T20:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
```

There are places in jsonld.js and/or rdf-canonize where it will just use `toString()` for all non-primitive JSON types.  I'm not sure if there is any special handling of js `Date`s at all?  In general, the APIs are designed to deal with cross platform JSON data.  It's usually better to just do the `toISOString()` part yourself, though I can understand how it's nice to use native js features.  The problem is that it would add overhead to do a conversion by checking all data for `Date`s.  That may be better left as an optional feature.

The order changes due to the algorithm that rdf-canonize is using.  It's partly based on hashes so the content can cause unpredictable yet deterministic reordering.

**Comment by krobi64** [comment] 2018-08-29 17:42
Here's my test:
```
const jsonld = require('..');
const should = require('chai').should()

describe('Give me an fn break', function() {

  const convertDateToUTC = (date) =>
    new Date(
      date.getUTCFullYear(),
      date.getUTCMonth(),
      date.getUTCDate(),
      date.getUTCHours(),
      date.getUTCMinutes(),
      date.getUTCSeconds()
    )

  const TheRaven = {
    '@context': {
      attributes: 'http://schema.org/CreativeWork',
      author: 'http://schema.org/author',
      text: 'http://schema.org/text',
      created: 'http://purl.org/dcterms/created',
      dateCreated: 'http://schema.org/dateCreated',
      datePublished: 'http://schema.org/datePublished',
      name: 'http://schema.org/name',
      tags: 'http://schema.org/keyword',
      type: 'http://schema.org/additionalType',
      publicKey: 'http://schema.org/Text',
    },
    id: 'c76146528c62dac83429217b6a7e159542b7a2d0c06432d6b7c9ba9cb3ebd39a',
    publicKey: '02badf4650ba545608242c2d303d587cf4f778ae3cf2b3ef99fbda37555a400fd2',
    type: 'Work',
    created: convertDateToUTC(new Date('2017-11-13T15:00:00.000Z')),
    attributes: {
      name: 'The Raven',
      author: 'Edgar Allan Poe',
      tags: 'poem',
      dateCreated: '',
      datePublished: '1845-01-29T03:00:00.000Z',
      text: 'Once upon a midnight dreary...',
    },
  }


  it('should create a deterministic result', async function() {
    const canonicalDoc = await jsonld.canonize(TheRaven).catch(e => e)
    console.log(`canonicalDoc ${canonicalDoc}`)

    const expected =
      '_:c14n0 <http://purl.org/dcterms/created> "Mon Nov 13 2017 15:00:00 GMT+0000 (UTC)" .\n' +
      '_:c14n0 <http://schema.org/CreativeWork> _:c14n1 .\n' +
      '_:c14n0 <http://schema.org/Text> "02badf4650ba545608242c2d303d587cf4f778ae3cf2b3ef99fbda37555a400fd2" .\n_:c14n0 <http://schema.org/additionalType> "Work" .\n_:c14n1 <http://schema.org/author> "Edgar Allan Poe" .\n_:c14n1 <http://schema.org/dateCreated> "" .\n' +
      '_:c14n1 <http://schema.org/datePublished> "1845-01-29T03:00:00.000Z" .\n' +
      '_:c14n1 <http://schema.org/keyword> "poem" .\n' +
      '_:c14n1 <http://schema.org/name> "The Raven" .\n' +
      '_:c14n1 <http://schema.org/text> "Once upon a midnight dreary..." .\n'

    canonicalDoc.should.equal(expected)
  })
})
```
It passes with node < 10.4 and fails with node >=10.4

I agree that pushing the responsibility back to us prevents unnecessary overhead in the library itself.

Thanks for explaining about the ordering. I was curious about that.

**Comment by dlongley** [comment] 2020-05-26 16:32
Closing as not an issue for this library. To get consistent results, use native string values not Date objects as values.

**Closed by dlongley** 2020-05-26 16:32 UTC
