### ISSUE TITLE
n-quads parse error when parsing quads with newlines

### ISSUE THREAD

**Issue by steffansluis** [digitalbazaar/jsonld.js#242] opened 2018-04-12 22:44 UTC
There seems to be a problem going back and forth with n-quads. If I start with the following JSON-LD document:
```json
[
  {
    "http://schema.org/name": [
      {
        "@value": "Jane\nDoe"
      }
    ]
  }
]
```

Convert it to n-quads:
```
_:b0 <http://schema.org/name> "Jane\nDoe" .
```

And then try to convert it back to JSON-LD:
```javascript
promises = require('jsonld').promises;
y = `_:b0 <http://schema.org/name> "Jane\nDoe" .`
jsonld.fromRDF(y).then(console.log.bind(console));
```

This result in the following error:
`Error: N-Quads parse error on line 1.`

This seems either unintended or unpredictable behaviour to me.

**Comment by steffansluis** [comment] 2018-04-12 22:48
Sorry for the strange first post, I pressed something strange and it posted. I updated it to actually make sense.

**Comment by davidlehn** [comment] 2018-04-12 23:24
Looks like the conversion to n-quads is not escaping the newline properly.  Then the parser gets upset.  Should be `"Jane\\nDoe"`?

**Comment by steffansluis** [comment] 2018-04-12 23:26
I think so, the [spec](https://www.w3.org/TR/n-quads/#sec-grammar) mentions newlines needing to be escaped. I'll take a look at the code...

**Comment by steffansluis** [comment] 2018-04-12 23:54
Ok, so looking at the `toRdf` implementation in this lib, the object of the quad returned is just the unescaped version of the string. I suppose this is the intended behaviour and the escaping is left up to the developer. The unintuitive part comes from the n-quads in the playground (which I used to convert my doc to n-quads) not being parseable by the method above because the newline is not escaped, due to the difference between JS/JSON and n-quads. `\n` is considered escaped in n-quads and not in JS/JSON. Simple adding `.replace(/\n/g, "\\n");` to your object string fixes the problem.

**Comment by davidlehn** [comment] 2018-04-13 00:06
I'm going to re-open this.  I think the escaping may be wrong, but it quickly becomes confusing!  It would seem a fromRDF(toRDF(data)) process should result in the same semantic data vs an error.  It looks like the json-ld.org test suite is lacking any toRdf/fromRdf tests that involve escaping, which should also be addressed.

**Comment by steffansluis** [comment] 2018-04-13 00:12
Ah, didn't look in to it that thoroughly, but if this is indeed the case than the issue should be re-opened. I figured I was just misinterpreting the output and the error was on my side (hence my closing it), but it doesn't hurt looking into this in either case. A test case is definitely a good idea. Let me know if you need anymore info, and many thanks for the quick response! :smiley:

**Comment by davidlehn** [comment] 2018-04-13 00:42
I think the code is ok.  We should add a few sanity check tests for this case though.  Or figure out how to use a n-quads test suite.  The confusion is probably when things are printed out and entered.
```
> console.log(quad)
_:b0 <http://schema.org/name> "Jane\nDoe" .
> quad
'_:b0 <http://schema.org/name> "Jane\\nDoe" .\n'
```
So it depends on how things get printed and if they show the escape chars or the escaped values.

Round trip test in the console passes (with added input blank node id):
```js
let d = [{"@id": "_:b0", "http://schema.org/name": [{"@value": "Jane\nDoe"}]}];
jsonld.toRDF(d, {format: 'application/n-quads'}).then(d2 => jsonld.fromRDF(d2)).then(d3 => assert.deepStrictEqual(d, d3));
```

**Comment by dlongley** [comment] 2020-05-26 23:24
Closing as fixed/not a bug.

**Closed by dlongley** 2020-05-26 23:24 UTC
