### ISSUE TITLE
Organize into modules

### ISSUE THREAD

**Issue by letmaik** [digitalbazaar/jsonld.js#136] opened 2016-03-23 09:39 UTC
I use this library in a browser context and only need a subset of its functionality. It would be great if the different parts of this package are split into separate modules/files (not packages!) such that I can import only certain functionality and have a smaller network footprint. For example, I don't need to run expansion or normalization algorithms and don't need the jquery or node document loaders.

**Comment by dlongley** [comment] 2016-03-23 14:20
@neothemachine,

This is being worked on in #126.

**Comment by davidlehn** [comment] 2018-01-25 23:30
Some progress has been made in 0.5.x.  It's still CJS but headed towards more module setup.

**Comment by dlongley** [comment] 2020-05-26 21:37
Closing as a duplicate of #399.

**Closed by dlongley** 2020-05-26 21:37 UTC
