### ISSUE TITLE
Update packages

### ISSUE THREAD

**Issue by Myasir92** [digitalbazaar/jsonld.js#483] opened 2022-04-28 07:57 UTC
Can you please update the dependent packages which are used in it because it works fine when we run it in the node application but when we run it as executable it shows a lot of errors and on our end, we solve that problem by going to the following package in node modules and try to update the packages and after updating it works fine?

**Comment by davidlehn** [comment] 2022-04-28 15:40
Can you be more specific about what you would like updated and what the problem is?

We'll be updating `@digitalbazaar/http-client` soon.  We're trying to get in some other patches first but might need to fast track that particular one.

**Comment by Myasir92** [comment] 2022-04-30 17:58
Yeah, I face an issue that shows an error in the `@digitalbazaar/http-client` package and when I update it, it solves my error.

**Comment by davidlehn** [comment] 2022-06-06 23:11
v6.0.0 released with @digitalbazaar/http-client v3.2.0.

**Closed by davidlehn** 2022-06-06 23:11 UTC
