### ISSUE TITLE
bin/jsonld expand says "Malformed URL"

### ISSUE THREAD

**Issue by mb21** [digitalbazaar/jsonld.js#64] opened 2014-06-18 12:10 UTC
$ ./bin/jsonld expand "http://www.markus-lanthaler.com/hydra/api-demo/"
    jsonld.InvalidUrl: Malformed URL.

Whereas this works:

    $ ./bub.jsonld format "http://www.markus-lanthaler.com/hydra/api-demo/"
    {
      "@context": "/hydra/api-demo/contexts/EntryPoint.jsonld",
      "@id": "/hydra/api-demo/",
      "@type": "EntryPoint",
      "issues": "/hydra/api-demo/issues/",
      "register_user": "/hydra/api-demo/users/",
      "users": "/hydra/api-demo/users/"
    }

And this works as well:

    $ cat test.js 
    var jsonld = require('jsonld');
    var promise = jsonld.promises().expand("http://www.markus-lanthaler.com/hydra/api-demo/")
        .then(function(extend) {
            console.log(extend);
        }, function(err) {
            console.error(err);
        });
    $ node test.js 
    [ { '@id': 'http://www.markus-lanthaler.com/hydra/api-demo/',
        '@type': [ 'http://www.markus-lanthaler.com/hydra/api-demo/vocab#EntryPoint' ],
        'http://www.markus-lanthaler.com/hydra/api-demo/vocab#EntryPoint/issues': [ [Object] ],
        'http://www.markus-lanthaler.com/hydra/api-demo/vocab#EntryPoint/registerUser': [ [Object] ],
        'http://www.markus-lanthaler.com/hydra/api-demo/vocab#EntryPoint/users': [ [Object] ] } ]

    $ ./jsonld --version
    0.2.13

**Comment by dlongley** [comment] 2015-08-27 15:28
Closing this as a duplicate of #29.

**Closed by dlongley** 2015-08-27 15:28 UTC
