### ISSUE TITLE
Using jsonld.js with rollup

### ISSUE THREAD

**Issue by lazka** [digitalbazaar/jsonld.js#355] opened 2020-01-15 16:07 UTC
Hey, more of a support question:

I'm trying to use jsonld.js with rollup for browser bundling and I was wondering if anyone has a working setup for it already or can give some hints on how to improve things (or can recommend an alternative library for parsing jsonld)

I can just import the minified version on npm, but that doesn't give me named exports and no treeshaking and jsonld.js is too large as is.

I have a minimal working rollup+jsonld setup here if someone wants to give it a try: https://github.com/lazka/jsonld-rollup-test

**Comment by omirobarcelo** [comment] 2020-04-08 13:29
Yes, I have also issues with rollup. I'm trying to use `jsonld` in a Svelte web app. 

These are my errors when building, using the library like `import * as jsonld from "jsonld"`:
```
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
core-js/fn/object/entries (imported by node_modules\jsonld\lib\index.js,  core-js/fn/object/entries?commonjs-external)
(!) Missing exports
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
src\App.svelte
compact is not exported by node_modules\jsonld\lib\index.js
360:   async function showData() {
361:     $$invalidate(1, show = true);
362:     const compacted = await jsonld.compact(doc, context);
                                        ^
363:     console.log(JSON.stringify(compacted, null, 2));
```

Using the minified version from `node_modules` liek @lazka does in his repo works, but it's not an ideal solution.

**Comment by lazka** [comment] 2020-04-09 07:54
I've just updated the example repo to jsonld 3.x and rollup 2.x. Minified no-op bundle size is still at 230kb

**Comment by davidlehn** [comment] 2020-04-09 23:29
Current focus is on 1.1 and related features.  After that I hope to see the code switch over to ESM style and do some related cleanups.  If using tree shaking tools then that should help with the size before even looking at other optimizations.

**Comment by dlongley** [comment] 2020-05-26 21:37
Closing as a duplicate of #399.

**Closed by dlongley** 2020-05-26 21:37 UTC

**Comment by lazka** [comment] 2020-05-27 05:26
Nice to see some progress, thanks!

**Comment by lazka** [comment] 2021-02-15 12:06
I've updated my example repo now (newer versions, not using the minified version): https://github.com/lazka/jsonld-rollup-test

We are down from 215kb to 115kb, which is a nice improvements.
