### ISSUE TITLE
npm install fails with node v0.11.15

### ISSUE THREAD

**Issue by kevinprotoss** [digitalbazaar/jsonld.js#87] opened 2015-01-26 08:20 UTC
Depends on

  - jsdom
  - contextify

```
child_process: customFds option is deprecated, use stdio instead.
make: Entering directory '/Invend/server/node_modules/juice/node_modules/jsdom/node_modules/contextify/build'
  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc: In destructor ‘virtual ContextifyContext::~ContextifyContext()’:
../src/contextify.cc:31:9: error: ‘ContextDisposedNotification’ is not a member of ‘v8::V8’
         v8::V8::ContextDisposedNotification();
         ^
contextify.target.mk:85: recipe for target 'Release/obj.target/contextify/src/contextify.o' failed
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
make: Leaving directory '/Invend/server/node_modules/juice/node_modules/jsdom/node_modules/contextify/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib64/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.15.5n-fuse
gyp ERR! command "node" "/usr/lib64/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Invend/server/node_modules/juice/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v0.11.15
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
```

**Comment by baslr** [comment] 2015-01-26 13:25
wrong repo see https://github.com/brianmcd/contextify/issues/146

**Comment by dlongley** [comment] 2015-02-11 02:44
Duplicate of #86.

**Closed by dlongley** 2015-02-11 02:44 UTC
